baseurl      = "https://gnuyent.dev"
title        = "gnuyent"
languageCode = "en-us"
theme        = "cactus"
copyright = "gnuyent"
publishDir   = "docs/"

# Metadata mostly used in document's head
description = "gnuyent"
keywords = "homepage, blog"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "/posts"
  weight = 2

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]
  colortheme = "white"
  rss = true

  # Home page settings
  description = "Hi! My name is Brandon. I'm a senior at San Diego State University studying Computer Science."
  mainSection = "posts"
  postsOnHomePage = 5
  tagsOverview = false
  projectsUrl = "https://github.com/gnuyent"
  showProjectsList = true

  # Post page settings
  show_updated = true
  showReadTime = true

  [params.comments]
    enabled = false

  [[params.social]]
    name = "email"
    link = "gnuyent@protonmail.com"

  [[params.social]]
    name = "github"
    link = "https://github.com/gnuyent"

  [[params.social]]
    name = "linkedin"
    link = "https://linkedin.com/in/brandonnguyen02"

